version: '3'

services:
  nginx404manager:
    container_name: Nginx-404-manager
    image: docker.minutesmade.com/mm-nginx-404-manager
    build:
      context: ./
    ports:
      - "5001:80"
    networks:
      - 404_net
    volumes:
      - 404-static-volume:/www/static

volumes:
  404-static-volume:

networks:
  404_net:
    driver: bridge
