version: '3'

services:
  nginx:
    container_name: NGINX
    image: www.minutesmade.com:8091/mm-nginx
    build:
      context: ./Nginx
    volumes:
      - ./MM404:/usr/mm/mm404
    ports:
      - "80:80"
    depends_on:
      - mm404

  redis-processing:
    container_name: redis-processing
    hostname: redis-processing
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes", "--port", "6379"]
    ports:
      - "6379:6379"

  redis-write:
    container_name: redis-write
    hostname: redis-write
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes", "--port", "6378"]
    ports:
      - "6378:6378"

  mmpulpfree:
    container_name: MM-PulpFree
    hostname: mmpulpfree
    command: ["node", "server"]
    tty: true
    build:
      context: ./MM-PulpFree
    working_dir: /usr/mm/mm-pulpfree/app
    volumes:
      - ./MM-PulpFree/app:/usr/mm/mm-pulpfree/app
    ports:
      - "8080:8080"

  mm404:
    container_name: MM404
    hostname: mm404
    image: www.minutesmade.com:8091/mm404
    command: ["gunicorn", "-k", "eventlet", "-w", "1", "main_mm404:app", "--bind=0.0.0.0:5000", "--no-sendfile"]
    tty: true
    build:
      context: ./MM404
    working_dir: /usr/mm/mm404
    volumes:
      - ./MM404:/usr/mm/mm404
    ports:
      - "5000:5000"
    depends_on:
      - redis-write
      - redis-processing

  mml:
    container_name: MML
    hostname: mml
    image: www.minutesmade.com:8091/mml
    command: ["python", "main_mml.py"]
    tty: true
    build:
      context: ./MML
    working_dir: /usr/mm/mml
    volumes:
      - ./MML:/usr/mm/mml
    depends_on:
      - redis-processing

  mmkoolaid:
    container_name: MM-Koolaid
    hostname: mmkoolaid
    command: ["hypercorn", "--config", "python:hypercorn.py", "main_mmkoolaid:create_app()"]
    tty: true
    build:
      context: ./MM-Koolaid
    working_dir: /usr/mm/mm-koolaid
    volumes:
      - ./MM-Koolaid:/usr/mm/mm-koolaid
    ports:
      - "5050:5050"
